language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: labguide/.vuepress/dist
  github-token: fe17e9b108cc62e2f47ea98ed542565e7cdab6e7 # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master